// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBVsqCvH0_ANcL5yhBhIGlaR1pENSpaGQ',
    appId: '1:314764495047:web:9142b823e2b8c5926116e2',
    messagingSenderId: '314764495047',
    projectId: 'docare-a94a9',
    authDomain: 'docare-a94a9.firebaseapp.com',
    storageBucket: 'docare-a94a9.appspot.com',
    measurementId: 'G-NSNQZZSE8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8JPHUWN5moy4xvSmVNIBhXxaveuA1CMI',
    appId: '1:314764495047:android:e19b532ede6c84e56116e2',
    messagingSenderId: '314764495047',
    projectId: 'docare-a94a9',
    storageBucket: 'docare-a94a9.appspot.com',
  );
}
